version: "3.5"

services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:9.2.1
    command: [
      "run",
      "--config", "/config/config.json",
      "--database-path", "/data/db",
      "--socket-path", "/ipc/node.socket",
      "--topology", "/config/topology.json"
    ]
    volumes:
      - ./cardano-configurations/network/preprod/cardano-node:/config
      - ./cardano-configurations/network/preprod/genesis:/genesis
      - node-preprod-db:/data
      - node-ipc:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
  
  ogmios:
    image: cardanosolutions/ogmios:v6.8.0
    volumes: 
      - node-ipc:/ipc
      - ./cardano-configurations/network/preprod:/config
    restart: on-failure
    ports: 
      - 1337:1337
    depends_on:
      - cardano-node
    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/cardano-node/config.json"
    ]

  kupo:
    image: cardanosolutions/kupo:v2.9.0
    depends_on:
      - cardano-node
    command:
      [
        '--node-socket', '/ipc/node.socket',
        '--node-config', '/configs/cardano-node/config.json',
        '--since', '44150423.1705a8d8b69cb1315de2b7d5569953f0bb4eddb685cead76c98a6082e835f888',
        '--match', '*',
        '--host', '0.0.0.0',
        '--workdir', '/db',
        '--prune-utxo'
      ]
    volumes:
      - ./cardano-configurations/network/preprod:/configs
      - node-ipc:/ipc
      - kupo-db:/db
    ports:
      - 1442:1442
    restart: on-failure

volumes:
  node-preprod-db:
  wallet-preprod-db:
  node-ipc:
  node-config:
  kupo-db: